/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PredictorRouteImport } from './routes/predictor'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as UsersRouteImport } from './routes/users'
import { Route as DriversIndexRouteImport } from './routes/drivers.index'
import { Route as DriversDriverIdRouteImport } from './routes/drivers.$driverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictorRoute = PredictorRouteImport.update({
  id: '/predictor',
  path: '/predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversDriverIdRoute = DriversDriverIdRouteImport.update({
  id: '/drivers/$driverId',
  path: '/drivers/$driverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dispatch': typeof DispatchRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/predictor': typeof PredictorRoute
  '/trips': typeof TripsRoute
  '/users': typeof UsersRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/drivers/': typeof DriversIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dispatch': typeof DispatchRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/predictor': typeof PredictorRoute
  '/trips': typeof TripsRoute
  '/users': typeof UsersRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/drivers': typeof DriversIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/dispatch': typeof DispatchRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/predictor': typeof PredictorRoute
  '/trips': typeof TripsRoute
  '/users': typeof UsersRoute
  '/drivers/$driverId': typeof DriversDriverIdRoute
  '/drivers/': typeof DriversIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/dispatch'
    | '/ledger'
    | '/login'
    | '/predictor'
    | '/trips'
    | '/users'
    | '/drivers/$driverId'
    | '/drivers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/dispatch'
    | '/ledger'
    | '/login'
    | '/predictor'
    | '/trips'
    | '/users'
    | '/drivers/$driverId'
    | '/drivers'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/dispatch'
    | '/ledger'
    | '/login'
    | '/predictor'
    | '/trips'
    | '/users'
    | '/drivers/$driverId'
    | '/drivers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  DispatchRoute: typeof DispatchRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  PredictorRoute: typeof PredictorRoute
  TripsRoute: typeof TripsRoute
  UsersRoute: typeof UsersRoute
  DriversDriverIdRoute: typeof DriversDriverIdRoute
  DriversIndexRoute: typeof DriversIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictor': {
      id: '/predictor'
      path: '/predictor'
      fullPath: '/predictor'
      preLoaderRoute: typeof PredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers/'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/$driverId': {
      id: '/drivers/$driverId'
      path: '/drivers/$driverId'
      fullPath: '/drivers/$driverId'
      preLoaderRoute: typeof DriversDriverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  DispatchRoute: DispatchRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  PredictorRoute: PredictorRoute,
  TripsRoute: TripsRoute,
  UsersRoute: UsersRoute,
  DriversDriverIdRoute: DriversDriverIdRoute,
  DriversIndexRoute: DriversIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
