spring:
  application:
    name: backend

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

#  datasource:
#    url: jdbc:postgresql://localhost:5432/routeledger
#    username: user
#    password: user
#    driver-class-name: org.postgresql.Driver


  datasource:
    url: jdbc:postgresql://database-1.cf0msciw8wcm.eu-north-1.rds.amazonaws.com:5432/routeledger
    username: routeledger_app
    password: ${ROUTELEDGER_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    # Spring AI (Google GenAI / Gemini) Configuration
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-2.5-flash

jwt:
  secret: ${JWT_KEY}
  expiration: 86400000

server:
  port: 8082

